2021-08-08 23:32:53,667 core INFO: DATALOADER:
  NUM_WORKERS: 8
  SIZE_DIVISIBILITY: 32
DATASETS:
  IGNORE_CHANNELS: (0,)
  NUM_CLASS: 2
  TEST: ('custom_dataset_test',)
  TRAIN: ('custom_dataset_train',)
  VAL: ('custom_dataset_val',)
INPUT:
  SIZE: 512
MODEL:
  ACTIVATION: softmax2d
  ARCHITECTURE: Unet
  DEVICE: cuda
  ENCODER: resnet50
  ENCODER_WEIGHTS: imagenet
  GPU_NUM: 0
  LOSS: DiceLoss
  METRICS: ('Dice',)
  WEIGHT: 
OUTPUT_DIR: .
PATHS_CATALOG: /home/kolton/semantic-segmentation-framework-pytorch/core/config/paths_catalog.py
SOLVER:
  BASE_LR: 0.001
  BIAS_LR_FACTOR: 2
  CHECKPOINT_PERIOD: 1
  DCONV_OFFSETS_LR_FACTOR: 1.0
  GAMMA: 0.1
  IMS_PER_BATCH_TEST: 1
  IMS_PER_BATCH_TRAIN: 8
  IMS_PER_BATCH_VAL: 1
  MAX_EPOCH: 80
  MOMENTUM: 0.9
  OPTIMIZER: Adam
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS: 0
2021-08-08 23:32:53,667 core INFO: Collecting env info (might take some time)
2021-08-08 23:32:56,992 core INFO: 
PyTorch version: 1.9.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.27

Python version: 3.8 (64-bit runtime)
Python platform: Linux-5.10.43.3-microsoft-standard-WSL2-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1660 Ti with Max-Q Design
Nvidia driver version: 471.11
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] efficientnet-pytorch==0.6.3
[pip3] numpy==1.21.1
[pip3] segmentation-models-pytorch==0.2.0
[pip3] torch==1.9.0
[pip3] torchvision==0.10.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2021.2.0           h06a4308_296  
[conda] mkl-service               2.3.0            py38h27cfd23_1  
[conda] mkl_fft                   1.3.0            py38h42c9631_2  
[conda] mkl_random                1.2.1            py38ha9443f7_2  
[conda] numpy                     1.20.2           py38h2d18471_0  
[conda] numpy-base                1.20.2           py38hfae3a4d_0  
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1
        Pillow (8.3.1)
2021-08-08 23:33:29,038 core.utils.checkpoint INFO: No checkpoint found. Initializing model from scratch
2021-08-08 23:33:55,828 core INFO: DATALOADER:
  NUM_WORKERS: 8
  SIZE_DIVISIBILITY: 32
DATASETS:
  IGNORE_CHANNELS: (0,)
  NUM_CLASS: 2
  TEST: ('custom_dataset_test',)
  TRAIN: ('custom_dataset_train',)
  VAL: ('custom_dataset_val',)
INPUT:
  SIZE: 512
MODEL:
  ACTIVATION: softmax2d
  ARCHITECTURE: Unet
  DEVICE: cuda
  ENCODER: resnet50
  ENCODER_WEIGHTS: imagenet
  GPU_NUM: 0
  LOSS: DiceLoss
  METRICS: ('Dice',)
  WEIGHT: 
OUTPUT_DIR: .
PATHS_CATALOG: /home/kolton/semantic-segmentation-framework-pytorch/core/config/paths_catalog.py
SOLVER:
  BASE_LR: 0.001
  BIAS_LR_FACTOR: 2
  CHECKPOINT_PERIOD: 1
  DCONV_OFFSETS_LR_FACTOR: 1.0
  GAMMA: 0.1
  IMS_PER_BATCH_TEST: 1
  IMS_PER_BATCH_TRAIN: 8
  IMS_PER_BATCH_VAL: 1
  MAX_EPOCH: 80
  MOMENTUM: 0.9
  OPTIMIZER: Adam
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS: 0
2021-08-08 23:33:55,828 core INFO: Collecting env info (might take some time)
2021-08-08 23:33:58,726 core INFO: 
PyTorch version: 1.9.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.27

Python version: 3.8 (64-bit runtime)
Python platform: Linux-5.10.43.3-microsoft-standard-WSL2-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1660 Ti with Max-Q Design
Nvidia driver version: 471.11
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] efficientnet-pytorch==0.6.3
[pip3] numpy==1.21.1
[pip3] segmentation-models-pytorch==0.2.0
[pip3] torch==1.9.0
[pip3] torchvision==0.10.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2021.2.0           h06a4308_296  
[conda] mkl-service               2.3.0            py38h27cfd23_1  
[conda] mkl_fft                   1.3.0            py38h42c9631_2  
[conda] mkl_random                1.2.1            py38ha9443f7_2  
[conda] numpy                     1.20.2           py38h2d18471_0  
[conda] numpy-base                1.20.2           py38hfae3a4d_0  
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1
        Pillow (8.3.1)
2021-08-08 23:34:02,802 core.utils.checkpoint INFO: No checkpoint found. Initializing model from scratch
2021-08-08 23:34:02,842 core.inference INFO: Start evaluation on custom_dataset_test dataset(18334 images).
2021-08-08 23:35:00,477 core INFO: DATALOADER:
  NUM_WORKERS: 8
  SIZE_DIVISIBILITY: 32
DATASETS:
  IGNORE_CHANNELS: (0,)
  NUM_CLASS: 2
  TEST: ('custom_dataset_test',)
  TRAIN: ('custom_dataset_train',)
  VAL: ('custom_dataset_val',)
INPUT:
  SIZE: 512
MODEL:
  ACTIVATION: softmax2d
  ARCHITECTURE: Unet
  DEVICE: cuda
  ENCODER: resnet50
  ENCODER_WEIGHTS: imagenet
  GPU_NUM: 0
  LOSS: DiceLoss
  METRICS: ('Dice',)
  WEIGHT: 
OUTPUT_DIR: .
PATHS_CATALOG: /home/kolton/semantic-segmentation-framework-pytorch/core/config/paths_catalog.py
SOLVER:
  BASE_LR: 0.001
  BIAS_LR_FACTOR: 2
  CHECKPOINT_PERIOD: 1
  DCONV_OFFSETS_LR_FACTOR: 1.0
  GAMMA: 0.1
  IMS_PER_BATCH_TEST: 1
  IMS_PER_BATCH_TRAIN: 8
  IMS_PER_BATCH_VAL: 1
  MAX_EPOCH: 80
  MOMENTUM: 0.9
  OPTIMIZER: Adam
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS: 0
2021-08-08 23:35:00,477 core INFO: Collecting env info (might take some time)
2021-08-08 23:35:03,557 core INFO: 
PyTorch version: 1.9.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.27

Python version: 3.8 (64-bit runtime)
Python platform: Linux-5.10.43.3-microsoft-standard-WSL2-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1660 Ti with Max-Q Design
Nvidia driver version: 471.11
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] efficientnet-pytorch==0.6.3
[pip3] numpy==1.21.1
[pip3] segmentation-models-pytorch==0.2.0
[pip3] torch==1.9.0
[pip3] torchvision==0.10.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2021.2.0           h06a4308_296  
[conda] mkl-service               2.3.0            py38h27cfd23_1  
[conda] mkl_fft                   1.3.0            py38h42c9631_2  
[conda] mkl_random                1.2.1            py38ha9443f7_2  
[conda] numpy                     1.20.2           py38h2d18471_0  
[conda] numpy-base                1.20.2           py38hfae3a4d_0  
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1
        Pillow (8.3.1)
2021-08-08 23:35:07,960 core.utils.checkpoint INFO: No checkpoint found. Initializing model from scratch
2021-08-08 23:35:08,013 core.inference INFO: Start evaluation on custom_dataset_test dataset(18334 images).
2021-08-08 23:36:38,384 core INFO: DATALOADER:
  NUM_WORKERS: 8
  SIZE_DIVISIBILITY: 32
DATASETS:
  IGNORE_CHANNELS: (0,)
  NUM_CLASS: 2
  TEST: ('custom_dataset_test',)
  TRAIN: ('custom_dataset_train',)
  VAL: ('custom_dataset_val',)
INPUT:
  SIZE: 512
MODEL:
  ACTIVATION: softmax2d
  ARCHITECTURE: Unet
  DEVICE: cuda
  ENCODER: resnet50
  ENCODER_WEIGHTS: imagenet
  GPU_NUM: 0
  LOSS: DiceLoss
  METRICS: ('Dice',)
  WEIGHT: 
OUTPUT_DIR: .
PATHS_CATALOG: /home/kolton/semantic-segmentation-framework-pytorch/core/config/paths_catalog.py
SOLVER:
  BASE_LR: 0.001
  BIAS_LR_FACTOR: 2
  CHECKPOINT_PERIOD: 1
  DCONV_OFFSETS_LR_FACTOR: 1.0
  GAMMA: 0.1
  IMS_PER_BATCH_TEST: 1
  IMS_PER_BATCH_TRAIN: 8
  IMS_PER_BATCH_VAL: 1
  MAX_EPOCH: 80
  MOMENTUM: 0.9
  OPTIMIZER: Adam
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS: 0
2021-08-08 23:36:38,384 core INFO: Collecting env info (might take some time)
2021-08-08 23:36:41,401 core INFO: 
PyTorch version: 1.9.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.27

Python version: 3.8 (64-bit runtime)
Python platform: Linux-5.10.43.3-microsoft-standard-WSL2-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1660 Ti with Max-Q Design
Nvidia driver version: 471.11
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] efficientnet-pytorch==0.6.3
[pip3] numpy==1.21.1
[pip3] segmentation-models-pytorch==0.2.0
[pip3] torch==1.9.0
[pip3] torchvision==0.10.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2021.2.0           h06a4308_296  
[conda] mkl-service               2.3.0            py38h27cfd23_1  
[conda] mkl_fft                   1.3.0            py38h42c9631_2  
[conda] mkl_random                1.2.1            py38ha9443f7_2  
[conda] numpy                     1.20.2           py38h2d18471_0  
[conda] numpy-base                1.20.2           py38hfae3a4d_0  
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1
        Pillow (8.3.1)
2021-08-08 23:36:45,578 core.utils.checkpoint INFO: No checkpoint found. Initializing model from scratch
2021-08-08 23:36:45,626 core.inference INFO: Start evaluation on custom_dataset_test dataset(18334 images).
2021-08-08 23:40:28,268 core INFO: DATALOADER:
  NUM_WORKERS: 8
  SIZE_DIVISIBILITY: 32
DATASETS:
  IGNORE_CHANNELS: (0,)
  NUM_CLASS: 2
  TEST: ('custom_dataset_test',)
  TRAIN: ('custom_dataset_train',)
  VAL: ('custom_dataset_val',)
INPUT:
  SIZE: 512
MODEL:
  ACTIVATION: softmax2d
  ARCHITECTURE: Unet
  DEVICE: cuda
  ENCODER: resnet50
  ENCODER_WEIGHTS: imagenet
  GPU_NUM: 0
  LOSS: DiceLoss
  METRICS: ('Dice',)
  WEIGHT: 
OUTPUT_DIR: .
PATHS_CATALOG: /home/kolton/semantic-segmentation-framework-pytorch/core/config/paths_catalog.py
SOLVER:
  BASE_LR: 0.001
  BIAS_LR_FACTOR: 2
  CHECKPOINT_PERIOD: 1
  DCONV_OFFSETS_LR_FACTOR: 1.0
  GAMMA: 0.1
  IMS_PER_BATCH_TEST: 1
  IMS_PER_BATCH_TRAIN: 8
  IMS_PER_BATCH_VAL: 1
  MAX_EPOCH: 80
  MOMENTUM: 0.9
  OPTIMIZER: Adam
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS: 0
2021-08-08 23:40:28,269 core INFO: Collecting env info (might take some time)
2021-08-08 23:40:31,351 core INFO: 
PyTorch version: 1.9.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.27

Python version: 3.8 (64-bit runtime)
Python platform: Linux-5.10.43.3-microsoft-standard-WSL2-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1660 Ti with Max-Q Design
Nvidia driver version: 471.11
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] efficientnet-pytorch==0.6.3
[pip3] numpy==1.21.1
[pip3] segmentation-models-pytorch==0.2.0
[pip3] torch==1.9.0
[pip3] torchvision==0.10.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2021.2.0           h06a4308_296  
[conda] mkl-service               2.3.0            py38h27cfd23_1  
[conda] mkl_fft                   1.3.0            py38h42c9631_2  
[conda] mkl_random                1.2.1            py38ha9443f7_2  
[conda] numpy                     1.20.2           py38h2d18471_0  
[conda] numpy-base                1.20.2           py38hfae3a4d_0  
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1
        Pillow (8.3.1)
2021-08-08 23:40:35,183 core.utils.checkpoint INFO: No checkpoint found. Initializing model from scratch
2021-08-08 23:40:35,227 core.inference INFO: Start evaluation on custom_dataset_test dataset(18334 images).
2021-08-08 23:42:34,397 core INFO: DATALOADER:
  NUM_WORKERS: 8
  SIZE_DIVISIBILITY: 32
DATASETS:
  IGNORE_CHANNELS: (0,)
  NUM_CLASS: 2
  TEST: ('custom_dataset_test',)
  TRAIN: ('custom_dataset_train',)
  VAL: ('custom_dataset_val',)
INPUT:
  SIZE: 512
MODEL:
  ACTIVATION: softmax2d
  ARCHITECTURE: Unet
  DEVICE: cuda
  ENCODER: resnet50
  ENCODER_WEIGHTS: imagenet
  GPU_NUM: 0
  LOSS: DiceLoss
  METRICS: ('Dice',)
  WEIGHT: 
OUTPUT_DIR: .
PATHS_CATALOG: /home/kolton/semantic-segmentation-framework-pytorch/core/config/paths_catalog.py
SOLVER:
  BASE_LR: 0.001
  BIAS_LR_FACTOR: 2
  CHECKPOINT_PERIOD: 1
  DCONV_OFFSETS_LR_FACTOR: 1.0
  GAMMA: 0.1
  IMS_PER_BATCH_TEST: 1
  IMS_PER_BATCH_TRAIN: 8
  IMS_PER_BATCH_VAL: 1
  MAX_EPOCH: 80
  MOMENTUM: 0.9
  OPTIMIZER: Adam
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS: 0
2021-08-08 23:42:34,397 core INFO: Collecting env info (might take some time)
2021-08-08 23:42:37,380 core INFO: 
PyTorch version: 1.9.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.27

Python version: 3.8 (64-bit runtime)
Python platform: Linux-5.10.43.3-microsoft-standard-WSL2-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1660 Ti with Max-Q Design
Nvidia driver version: 471.11
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] efficientnet-pytorch==0.6.3
[pip3] numpy==1.21.1
[pip3] segmentation-models-pytorch==0.2.0
[pip3] torch==1.9.0
[pip3] torchvision==0.10.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2021.2.0           h06a4308_296  
[conda] mkl-service               2.3.0            py38h27cfd23_1  
[conda] mkl_fft                   1.3.0            py38h42c9631_2  
[conda] mkl_random                1.2.1            py38ha9443f7_2  
[conda] numpy                     1.20.2           py38h2d18471_0  
[conda] numpy-base                1.20.2           py38hfae3a4d_0  
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1
        Pillow (8.3.1)
2021-08-08 23:42:41,304 core.utils.checkpoint INFO: No checkpoint found. Initializing model from scratch
2021-08-08 23:42:41,359 core.inference INFO: Start evaluation on custom_dataset_test dataset(18334 images).
2021-08-08 23:43:40,841 core INFO: DATALOADER:
  NUM_WORKERS: 8
  SIZE_DIVISIBILITY: 32
DATASETS:
  IGNORE_CHANNELS: (0,)
  NUM_CLASS: 2
  TEST: ('custom_dataset_test',)
  TRAIN: ('custom_dataset_train',)
  VAL: ('custom_dataset_val',)
INPUT:
  SIZE: 512
MODEL:
  ACTIVATION: softmax2d
  ARCHITECTURE: Unet
  DEVICE: cuda
  ENCODER: resnet50
  ENCODER_WEIGHTS: imagenet
  GPU_NUM: 0
  LOSS: DiceLoss
  METRICS: ('Dice',)
  WEIGHT: 
OUTPUT_DIR: .
PATHS_CATALOG: /home/kolton/semantic-segmentation-framework-pytorch/core/config/paths_catalog.py
SOLVER:
  BASE_LR: 0.001
  BIAS_LR_FACTOR: 2
  CHECKPOINT_PERIOD: 1
  DCONV_OFFSETS_LR_FACTOR: 1.0
  GAMMA: 0.1
  IMS_PER_BATCH_TEST: 1
  IMS_PER_BATCH_TRAIN: 8
  IMS_PER_BATCH_VAL: 1
  MAX_EPOCH: 80
  MOMENTUM: 0.9
  OPTIMIZER: Adam
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS: 0
2021-08-08 23:43:40,841 core INFO: Collecting env info (might take some time)
2021-08-08 23:43:43,861 core INFO: 
PyTorch version: 1.9.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.27

Python version: 3.8 (64-bit runtime)
Python platform: Linux-5.10.43.3-microsoft-standard-WSL2-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1660 Ti with Max-Q Design
Nvidia driver version: 471.11
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] efficientnet-pytorch==0.6.3
[pip3] numpy==1.21.1
[pip3] segmentation-models-pytorch==0.2.0
[pip3] torch==1.9.0
[pip3] torchvision==0.10.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2021.2.0           h06a4308_296  
[conda] mkl-service               2.3.0            py38h27cfd23_1  
[conda] mkl_fft                   1.3.0            py38h42c9631_2  
[conda] mkl_random                1.2.1            py38ha9443f7_2  
[conda] numpy                     1.20.2           py38h2d18471_0  
[conda] numpy-base                1.20.2           py38hfae3a4d_0  
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1
        Pillow (8.3.1)
2021-08-08 23:43:48,008 core.utils.checkpoint INFO: No checkpoint found. Initializing model from scratch
2021-08-08 23:43:48,081 core.inference INFO: Start evaluation on custom_dataset_test dataset(18334 images).
2021-08-08 23:45:06,152 core INFO: DATALOADER:
  NUM_WORKERS: 8
  SIZE_DIVISIBILITY: 32
DATASETS:
  IGNORE_CHANNELS: (0,)
  NUM_CLASS: 2
  TEST: ('custom_dataset_test',)
  TRAIN: ('custom_dataset_train',)
  VAL: ('custom_dataset_val',)
INPUT:
  SIZE: 512
MODEL:
  ACTIVATION: softmax2d
  ARCHITECTURE: Unet
  DEVICE: cuda
  ENCODER: resnet50
  ENCODER_WEIGHTS: imagenet
  GPU_NUM: 0
  LOSS: DiceLoss
  METRICS: ('Dice',)
  WEIGHT: 
OUTPUT_DIR: .
PATHS_CATALOG: /home/kolton/semantic-segmentation-framework-pytorch/core/config/paths_catalog.py
SOLVER:
  BASE_LR: 0.001
  BIAS_LR_FACTOR: 2
  CHECKPOINT_PERIOD: 1
  DCONV_OFFSETS_LR_FACTOR: 1.0
  GAMMA: 0.1
  IMS_PER_BATCH_TEST: 1
  IMS_PER_BATCH_TRAIN: 8
  IMS_PER_BATCH_VAL: 1
  MAX_EPOCH: 80
  MOMENTUM: 0.9
  OPTIMIZER: Adam
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS: 0
2021-08-08 23:45:06,152 core INFO: Collecting env info (might take some time)
2021-08-08 23:45:09,164 core INFO: 
PyTorch version: 1.9.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.27

Python version: 3.8 (64-bit runtime)
Python platform: Linux-5.10.43.3-microsoft-standard-WSL2-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1660 Ti with Max-Q Design
Nvidia driver version: 471.11
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] efficientnet-pytorch==0.6.3
[pip3] numpy==1.21.1
[pip3] segmentation-models-pytorch==0.2.0
[pip3] torch==1.9.0
[pip3] torchvision==0.10.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2021.2.0           h06a4308_296  
[conda] mkl-service               2.3.0            py38h27cfd23_1  
[conda] mkl_fft                   1.3.0            py38h42c9631_2  
[conda] mkl_random                1.2.1            py38ha9443f7_2  
[conda] numpy                     1.20.2           py38h2d18471_0  
[conda] numpy-base                1.20.2           py38hfae3a4d_0  
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1
        Pillow (8.3.1)
2021-08-08 23:45:13,308 core.utils.checkpoint INFO: No checkpoint found. Initializing model from scratch
2021-08-08 23:45:13,369 core.inference INFO: Start evaluation on custom_dataset_test dataset(18334 images).
